services:
  client:
    container_name: cruise-drop-recording-app
    image: react-cruise
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - container_data:/app/node_modules
    ports:
      - '3001:3001'
      - '4173:4173'

volumes:
  container_data:
    driver: local
    name: cruise-drop-recording-app-data
