# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Set up Node.js (using the version that your project requires)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'  # You can adjust this to the Node.js version you need
    
    # Install dependencies
    - name: Install dependencies
      run: npm install  # Use yarn or other package managers if that's your choice
    
    # Build the Vite project
    - name: Build Vite app
      run: npm run build  # This will generate the 'dist' folder by default

    # Upload build output as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: dist  # Upload the build output directory

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token for actions
        artifact_name: github-pages  # Specify the artifact name to deploy

